# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [5]:
import numpy as np
l = int(input('Length of array'))
a = np.ones((l, l)) * 6
print(a)
a[1:-1, 1: -1] = 0
print(a)

Length of array4
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]
[[6. 6. 6. 6.]
 [6. 0. 0. 6.]
 [6. 0. 0. 6.]
 [6. 6. 6. 6.]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [16]:
l = int(input('Length of array '))
a = np.ones((l, l)) * 3
a[::2, 1::2] = 9
a[1::2, ::2] = 9
print(a)

Length of array 8
[[3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [17]:
x = np.empty((3,3))
y = np.full((3,3), 6)
print(x)
print(y)

[[6.95241183e-310 6.95241183e-310 4.27328938e-037]
 [4.27932310e-033 7.17023480e-144 1.50008929e+248]
 [1.33500603e+253 2.42092166e-322 6.95241183e-310]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [18]:
farenheit = np.array([0, 12, 45.21 ,34, 99.91])
celcius = (farenheit - 32) * 5/9
print(celcius)

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [24]:
comp = np.array([ 1.00000000+0.j, 0.70710678+0.70710678j])
print('Real part-\n', comp.real)
print('Imaginary part -\n', comp.imag)

Real part-
 [1.         0.70710678]
Imaginary part -
 [0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [1]:
input_array = [0, 10, 20, 40, 60]
array_compare = [0, 40]
l = []
for ele in input_array:
    if ele in array_compare:
        l.append(True)
    else:
        l.append(False)
print(l)

[True, False, False, True, False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [3]:
input_array = [0, 10, 20, 40, 60]
array_compare = [10, 30, 40]
l = []
for ele in input_array:
    if ele in array_compare:
        l.append(ele)
print(l)

[10, 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [6]:
a = np.array([10, 10, 20, 20, 30, 30])
print(np.unique(a))
b = np.array([[1, 1],[2, 3]])
print(np.unique(b))

[10 20 30]
[1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [7]:
input_array = [0, 10, 20, 40, 60]
array_compare = [10, 30, 40, 50, 70]
l = []
for ele in input_array:
    if ele not in array_compare:
        l.append(ele)
for ele in array_compare:
    if ele not in input_array:
        l.append(ele)
print(l)

[0, 20, 60, 30, 50, 70]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [9]:
input_array = [0, 10, 20, 40, 60]
print(np.all(input_array))

False


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [10]:
input_array = [0, 10, 20, 40, 60]
print(np.all(input_array, axis=0))

False


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [12]:
sample = [1, 2, 3, 4]
n = int(input('Enter no of repetition :'))
print('Original array: \n', sample)
output = np.tile(sample, n)
print('Output array : \n', output)

Enter no of repetition :4
Original array: 
 [1, 2, 3, 4]
Output array : 
 [1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [13]:
input_array = [1, 2, 3, 4, 5, 6]
print('Original array: ', input_array)
print('Maximum value: ', np.argmax(input_array))
print('Minimum value: ', np.argmin(input_array))

Original array:  [1, 2, 3, 4, 5, 6]
Maximum value:  5
Minimum value:  0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [15]:
a = [1, 2]
b = [4, 5]
print("Array a: ",a)
print("Array b: ",b)
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))

Array a:  [1, 2]
Array b:  [4, 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [20]:
sample = [[4, 6], [2, 1]]
print('Original axis: \n', sample)
print('Sorting along first axis\n', np.sort(sample, axis=0))
print('Sorting along last axis\n', np.sort(sample, axis=-1))

Original axis: 
 [[4, 6], [2, 1]]
Sorting along first axis
 [[2 1]
 [4 6]]
Sorting along last axis
 [[4 6]
 [1 2]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [27]:
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)

[1 3 2 4 0]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [25]:
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
a = np.where(x > 10)
print("Values bigger than 10 =", a)
print("Their indices are ", x[a])

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = (array([0, 1, 1, 1]), array([2, 0, 1, 2]))
Their indices are  [20 20 30 40]


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [26]:
import numpy as np
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


## Great Job!